// IL FAUT UNE CLASS CARTE AVEC UN NOMBRE ET UN TYPE
// IL FAUT UNE CLASS JOUEUR AVEC UN NOM ET UNE CARTE ET UN NOMBRE DE VIE 
// IL FAUT UNE CLASS PLAY QU VA SE CHARGER DE DEMARRER LE JEU AVEC UNE FONCTION POUR LANCER LE JEU ET UNE AUTRE POUR ARRETER
// IL FAUT UNE CLASS PIOCHE POUR GERER LA DISTRIBUTION DE CARTE



